// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// This file is generated by assert.pl

namespace Microsoft
{
#if (ESENT)
namespace Windows
#else
namespace Exchange
#endif
{
namespace Isam
{

// JET_Assert* appears as #defines in jet.h, we rename them slightly (dropping JET_Assert)

MSINTERNAL enum class MJET_ASSERT
{
    Exit = 0x0000, // Exit the application
    Break = 0x0001, // Break to debugger
    MsgBox = 0x0002, // Display message box
    Stop = 0x0004, // Alert and stop
    SkippableMsgBox = 0x0008, // Display skippable message box
    SkipAll = 0x0010, // Skip all asserts
    Crash = 0x0020, // AV (*0=0 style)
    FailFast = 0x0040, // Use the Windows RaiseFailFastException API to force a crash
};

}
}
}
