// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// This file is generated by coltyps.pl

namespace Microsoft
{
#if (ESENT)
namespace Windows
#else
namespace Exchange
#endif
{
namespace Isam
{
// JET_coltyp* appears as #defines in jet.h, we rename them slightly (dropping JET_coltyp) to
// avoid a preprocessor nightmare

MSINTERNAL enum class MJET_COLTYP
{

    Nil = 0,
    Bit = 1,    // True, False, or NULL
    UnsignedByte = 2,   // 1-byte integer, unsigned
    Short = 3,  // 2-byte integer, signed
    Long = 4,   // 4-byte integer, signed
    Currency = 5,   // 8 byte integer, signed
    IEEESingle = 6, // 4-byte IEEE single precision
    IEEEDouble = 7, // 8-byte IEEE double precision
    DateTime = 8,   // Integral date, fractional time
    Binary = 9, // Binary data, < 255 bytes
    Text = 10,  // ANSI text, case insensitive, < 255 bytes
    LongBinary = 11,    // Binary data, long value
    LongText = 12,  // ANSI text, long value
    UnsignedLong = 14,  // 4-byte unsigned integer
    LongLong = 15,  // 8-byte signed integer
    GUID = 16,  // 16-byte globally unique identifier
    UnsignedShort = 17, // 2-byte unsigned integer
    UnsignedLongLong = 18,  // 8-byte unsigned integer
    Max = 19,   // the number of column types

};

}
}
}
