// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// This file is generated by exception.pl

namespace Microsoft
{
#if (ESENT)
namespace Windows
#else
namespace Exchange
#endif
{
namespace Isam
{

// JET_Exception* appears as #defines in jet.h, we rename them slightly (dropping JET_Exception)

MSINTERNAL enum class MJET_EXCEPTION
{
    MsgBox = 0x0001, // Display message box on exception
    None = 0x0002, // Do nothing on exceptions
    FailFast = 0x0004, // Use the Windows RaiseFailFastException API to force a crash
};

}
}
}
