// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// This file is generated by move.pl

namespace Microsoft
{
#if (ESENT)
namespace Windows
#else
namespace Exchange
#endif
{
namespace Isam
{

// JET_Move* appears as #defines in jet.h, we rename them slightly (dropping JET_Move) to

// The compiler doesn't believe that 0x80000000 will fit in to a signed int, so we get
// a warning. Instead we'll use INT_MIN, which is the same bit value.
// Converting MJET_GRIT to be an unsigned enum is a nuisance, since CLR is much happier
// with signed numbers.
C_ASSERT( 0x80000000 == INT_MIN );

MSINTERNAL enum class MJET_MOVE
{
    First = INT_MIN,
    Previous = (-1),
    Next = (+1),
    Last = (0x7fffffff),
};

}
}
}
