// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.


namespace Microsoft
{
#if (ESENT)
namespace Windows
#else
namespace Exchange
#endif
{
namespace Isam
{


MSINTERNAL enum class MJET_PARAM
{

    SystemPath = 0,
    TempPath = 1,
    LogFilePath = 2,
    BaseName = 3,
    EventSource = 4,
    MaxSessions = 5,
    MaxOpenTables = 6,
    PreferredMaxOpenTables = 7,
    CachedClosedTables = 125,
    MaxCursors = 8,
    MaxVerPages = 9,
    PreferredVerPages = 63,
    GlobalMinVerPages = 81,
    VersionStoreTaskQueueMax = 105,
    MaxTemporaryTables = 10,
    LogFileSize = 11,
    LogBuffers = 12,
    WaitLogFlush = 13,
    LogCheckpointPeriod = 14,
    LogWaitingUserMax = 15,
    CommitDefault = 16,
    CircularLog = 17,
    DbExtensionSize = 18,
    PageTempDBMin = 19,
    PageFragment = 20,
    PageReadAheadMax = 21,
    EnableFileCache = 126,
    VerPageSize = 128,
    Configuration = 129,
    EnableAdvanced = 130,
    MaxColtyp = 131,
    BatchIOBufferMax = 22,
    CacheSize = 41,
    CacheSizeMin = 60,
    CacheSizeMax = 23,
    CheckpointDepthMax = 24,
    LRUKCorrInterval = 25,
    LRUKHistoryMax = 26,
    LRUKPolicy = 27,
    LRUKTimeout = 28,
    LRUKTrxCorrInterval = 29,
    OutstandingIOMax = 30,
    StartFlushThreshold = 31,
    StopFlushThreshold = 32,
    TableClassName = 33,
    IdleFlushTime = 106,
    VAReserve = 109,
    DBAPageAvailMin = 120,
    DBAPageAvailThreshold = 121,
    DBAK1 = 122,
    DBAK2 = 123,
    MaxRandomIOSize = 124,
    EnableViewCache = 127,
    CheckpointIOMax = 135,
    TableClass1Name = 137,
    TableClass2Name = 138,
    TableClass3Name = 139,
    TableClass4Name = 140,
    TableClass5Name = 141,
    TableClass6Name = 142,
    TableClass7Name = 143,
    TableClass8Name = 144,
    TableClass9Name = 145,
    TableClass10Name = 146,
    TableClass11Name = 147,
    TableClass12Name = 148,
    TableClass13Name = 149,
    TableClass14Name = 150,
    TableClass15Name = 151,
    TableClass16Name = 196,
    TableClass17Name = 197,
    TableClass18Name = 198,
    TableClass19Name = 199,
    TableClass20Name = 200,
    TableClass21Name = 201,
    TableClass22Name = 202,
    TableClass23Name = 203,
    TableClass24Name = 204,
    TableClass25Name = 205,
    TableClass26Name = 206,
    TableClass27Name = 207,
    TableClass28Name = 208,
    TableClass29Name = 209,
    TableClass30Name = 210,
    TableClass31Name = 211,
    IOPriority = 152,
    Recovery = 34,
    OnLineCompact = 35,
    EnableOnlineDefrag = 35,
    AssertAction = 36,
    PrintFunction = 37,
    TransactionLevel = 38,
    RFS2IOsPermitted = 39,
    RFS2AllocsPermitted = 40,
    CacheRequests = 42,
    CacheHits = 43,
    CheckFormatWhenOpenFail = 44,
    EnableTempTableVersioning = 46,
    IgnoreLogVersion = 47,
    DeleteOldLogs = 48,
    EventSourceKey = 49,
    NoInformationEvent = 50,
    EventLoggingLevel = 51,
    DeleteOutOfRangeLogs = 52,
    AccessDeniedRetryPeriod = 53,
    EnableIndexChecking = 45,
    EnableIndexCleanup = 54,
    Flight_SmoothIoTestPermillage = 55,
    Flight_ElasticWaypointLatency = 56,
    Flight_SynchronousLVCleanup = 57,
    Flight_RBSRevertIOUrgentLevel = 58,
    Flight_EnableXpress10Compression = 59,
    LogFileFailoverPath = 61,
    EnableImprovedSeekShortcut = 62,
    DatabasePageSize = 64,
    DisableCallbacks = 65,
    AbortRetryFailCallback = 108,
    BackupChunkSize = 66,
    BackupOutstandingReads = 67,
    LogFileCreateAsynch = 69,
    ErrorToString = 70,
    ZeroDatabaseDuringBackup = 71,
    UnicodeIndexDefault = 72,
    RuntimeCallback = 73,
    Flight_EnableReattachRaceBugFix = 74,
    EnableSortedRetrieveColumns = 76,
    CleanupMismatchedLogFiles = 77,
    RecordUpgradeDirtyLevel = 78,
    RecoveryCurrentLogfile = 79,
    ReplayingReplicatedLogfiles = 80,
    OSSnapshotTimeout = 82,
    Flight_NewQueueOptions = 84,
    Flight_ConcurrentMetedOps = 85,
    Flight_LowMetedOpsThreshold = 86,
    Flight_MetedOpStarvedThreshold = 87,
    Flight_EnableShrinkArchiving = 89,
    Flight_EnableBackupDuringRecovery = 90,
    Flight_RBSRollIntervalSec = 91,
    Flight_RBSMaxRequiredRange = 92,
    Flight_RBSCleanupEnabled = 93,
    Flight_RBSLowDiskSpaceThresholdGb = 94,
    Flight_RBSMaxSpaceWhenLowDiskSpaceGb = 95,
    Flight_RBSMaxTimeSpanSec = 96,
    Flight_RBSCleanupIntervalMinSec = 97,
    ExceptionAction = 98,
    EventLogCache = 99,
    CreatePathIfNotExist = 100,
    PageHintCacheSize = 101,
    OneDatabasePerSession = 102,
    MaxDatabasesPerInstance = 103,
    MaxInstances = 104,
    DisablePerfmon = 107,
    IndexTuplesLengthMin = 110,
    IndexTuplesLengthMax = 111,
    IndexTuplesToIndexMax = 112,
    AlternateDatabaseRecoveryPath = 113,
    IndexTupleIncrement = 132,
    IndexTupleStart = 133,
    KeyMost = 134,
    LegacyFileNames = 136,
    EnablePersistedCallbacks = 156,
    WaypointLatency = 153,
    CheckpointTooDeep = 154,
    DisableBlockVerification = 155,
    AggressiveLogRollover = 157,
    PeriodicLogRolloverLLR = 158,
    UsePageDependencies = 159,
    DefragmentSequentialBTrees = 160,
    DefragmentSequentialBTreesDensityCheckFrequency = 161,
    IOThrottlingTimeQuanta = 162,
    LVChunkSizeMost = 163,
    MaxCoalesceReadSize = 164,
    MaxCoalesceWriteSize = 165,
    MaxCoalesceReadGapSize = 166,
    MaxCoalesceWriteGapSize = 167,
    EnableHaPublish = 168,
    EnableDBScanInRecovery = 169,
    DbScanThrottle = 170,
    DbScanIntervalMinSec = 171,
    DbScanIntervalMaxSec = 172,
    EmitLogDataCallback = 173,
    EmitLogDataCallbackCtx = 174,
    EnableExternalAutoHealing = 175,
    PatchRequestTimeout = 176,
    CachePriority = 177,
    MaxTransactionSize = 178,
    PrereadIOMax = 179,
    EnableDBScanSerialization = 180,
    HungIOThreshold = 181,
    HungIOActions = 182,
    MinDataForXpress = 183,
    EnableShrinkDatabase = 184,
    ProcessFriendlyName = 186,
    DurableCommitCallback = 187,
    EnableSqm = 188,
    ConfigStoreSpec = 189,
    StageFlighting = 190,
    ZeroDatabaseUnusedSpace = 191,
    DisableVerifications = 192,
    PersistedLostFlushDetection = 193,
    EngineFormatVersion = 194,
    ReplayThrottlingLevel = 195,
    BlockCacheConfiguration = 212,
    RecordSizeMost = 213,
    UseFlushForWriteDurability = 214,
    EnableRBS = 215,
    RBSFilePath = 216,
    MaxValueInvalid = 217,
};

}
}
}
